# Generated by Django 4.1.5 on 2023-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assetsData", "0003_delete_complaints"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="login_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
